#!/usr/bin/env bash

# vim:syntax=sh filetype=sh

set -e

if [ $(id -u) = 0 ]; then
	echo "$0 script need to run as regular user!"
	exit 1
fi

while [[ "$1" != "" ]]; do
    case $1 in
        -t|--tmp)  shift
            TMP=$1
        ;;
		-l|--log)  shift
            LOG=$1
        ;;
    esac
    shift
done
echo $LOG
IDU="$(id -u)"
IDG="$(id -g)"

CURDIR=$(cd "$(dirname $0)" && pwd)
SCRDIR=$CURDIR/scripts

source $SCRDIR/fn

if [ ! -d $LFS ]; then
	sudo mkdir -pv $LFS
fi

if [ ! -d $LFS/tools ]; then
	sudo mkdir -pv $LFS/tools
fi

if [ ! -w $LFS/tools ]; then
	sudo chown -R $IDU:$IDG $LFS/tools
fi

if [ ! -L /tools ] || [ $(realpath /tools) != $LFS/tools ]; then
	sudo ln -sv $LFS/tools /
fi

for script in $(ls $SCRDIR | grep ^[0-9]); do
	if [ "$1" = "fetch" ]; then
		SRC=$LFS/var/cache/scratchpkg/sources LOG=$LOG TMP=$TMP $SCRDIR/$script "$1"
	elif [ -f /tools/"$script" ]; then
		echo "--- $script skipped ---"
	else
		echo "*** $script ***"
		SRC=$LFS/var/cache/scratchpkg/sources LOG=$LOG TMP=$TMP $SCRDIR/$script
		echo; echo "*** $script done ***"; echo
		[ "$1" = $(echo $script | cut -d - -f1) ] && exit
	fi
done

[ "$1" = "fetch" ] && exit 0

sudo chown -R 0:0 $LFS

echo
echo "**************************************************"
echo "*********    Toolchain build complete    *********"
echo "**************************************************"
