#!/usr/bin/env bash

# vim:syntax=sh filetype=sh

set -e

source $(dirname $0)/fn
source $(dirname $0)/version

filename=$(fname $0)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=linux
VERSION=${LINUX_VER}

fetch "https://www.kernel.org/pub/linux/kernel/v5.x/linux-$LINUX_VER.tar.xz" "$SRC"

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

extract "$SRC/$tarballname" "$TMP"

{ time \
	{
		cd $TMP/$NAME-$VERSION
	
		make mrproper
		make headers
		cp -rv usr/include/* /tools/include
	}
} 2>&1 | tee $LOG/$filename.log

[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
