#!/usr/bin/env bash

# vim:syntax=sh filetype=sh

set -e

source $(dirname $0)/fn
source $(dirname $0)/version

filename=$(fname $0)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=glibc
VERSION=${GLIBC_VER}

fetch "http://ftp.gnu.org/gnu/glibc/glibc-$GLIBC_VER.tar.xz" "$SRC"

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

extract "$SRC/$tarballname" "$TMP"

{ time \
	{
		cd $TMP/$NAME-$VERSION

		mkdir -v build
		cd       build
		
		../configure                             \
			--prefix=/tools                    \
			--host=$LFS_TGT                    \
			--build=$(../scripts/config.guess) \
			--enable-kernel=3.2             \
			--with-headers=/tools/include
		make
		make install

		echo 'int main(){}' > dummy.c
		$LFS_TGT-gcc dummy.c
		readelf -l a.out | grep ': /tools'

		rm -v dummy.c a.out
	}
} 2>&1 | tee $LOG/$filename.log

[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
