#!/usr/bin/env bash

# vim:syntax=sh filetype=sh

set -e

source $(dirname $0)/fn
source $(dirname $0)/version

filename=$(fname $0)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=perl
VERSION=${PERL_VER}

fetch "https://www.cpan.org/src/5.0/perl-$PERL_VER.tar.xz" "$SRC"

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

extract "$SRC/$tarballname" "$TMP"

{ time \
	{
		cd $TMP/$NAME-$VERSION

		sh Configure -des -Dprefix=/tools -Dlibs=-lm -Uloclibpth -Ulocincpth
		make
		cp -v perl cpan/podlators/scripts/pod2man /tools/bin
		mkdir -pv /tools/lib/perl5/$VERSION
		cp -Rv lib/* /tools/lib/perl5/$VERSION
	}
} 2>&1 | tee $LOG/$filename.log

[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
