#!/usr/bin/env bash

# vim:syntax=sh filetype=sh

set -e

source $(dirname $0)/fn
source $(dirname $0)/version

filename=$(fname $0)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=openssl
VERSION=${OPENSSL_VER}

fetch "https://openssl.org/source/openssl-$OPENSSL_VER.tar.gz" "$SRC"

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

extract "$SRC/$tarballname" "$TMP"

{ time \
	{
		cd $TMP/$NAME-$VERSION

		./config --prefix=/tools             \
			--openssldir=/tools/etc/ssl \
			--libdir=lib                \
			shared                      \
			no-ssl3-method
		make
		make -j1 MANDIR=/tools/share/man MANSUFFIX=ssl install
	}
} 2>&1 | tee $LOG/$filename.log

[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
