#!/usr/bin/env bash

# vim:syntax=sh filetype=sh

set -e

source $(dirname $0)/fn
source $(dirname $0)/version

filename=$(fname $0)

TMP=${TMP:-/tmp/build}
LOG=${LOG:-$(dirname $0)/log}
SRC=${SRC:-$(dirname $0)/src}

NAME=wget
VERSION=${WGET_VER}

fetch "https://ftp.gnu.org/gnu/wget/wget-$WGET_VER.tar.gz" "$SRC"

[ "$1" = "fetch" ] && exit 0

rm -fr $TMP
mkdir -p $TMP $LOG $SRC

extract "$SRC/$tarballname" "$TMP"

{ time \
	{
		cd $TMP/$NAME-$VERSION
    
        ./configure OPENSSL_CFLAGS=-I/tools/include OPENSSL_LIBS="-L/tools/lib -lssl -lcrypto" \
                    --prefix=/tools    \
                    --sysconfdir=/tools/etc \
                    --with-ssl=openssl \
                    --without-libidn   \
                    --without-libpsl   \
                    --without-metalink \
                    --disable-pcre2
        make
        make install
        
        echo "ca_certificate = /tools/etc/ssl/certs/ca-certificates.crt" > /tools/etc/wgetrc
	}
} 2>&1 | tee $LOG/$filename.log

[ $PIPESTATUS = 0 ] && echo "$NAME-$VERSION" > /tools/$filename || exit $PIPESTATUS

rm -fr $TMP
